"""
marketmate.agent.pipeline
──────────────────────────
LangGraph-based agent pipeline for the MATE AI system.

Creates a graph-based workflow that routes queries through different
brains and tools. Falls back to a simple LLM-direct pipeline when
langgraph is not installed.

Pipeline Graph:
    ┌─────────┐     ┌───────┐     ┌───────────────┐     ┌───────────┐
    │ router  │────▶│ brain │────▶│ tool_executor │────▶│ formatter │
    └─────────┘     └───────┘     └───────────────┘     └───────────┘
                         │                                    ▲
                         │        (skip tools)                │
                         └────────────────────────────────────┘

Nodes:
  router        — Classifies the query and routes to the right brain
  brain         — Executes the appropriate brain module
  tool_executor — Executes tool calls if the brain decides tools are needed
  formatter     — Formats the final response for delivery

State keys:
  query         — The original user query (str)
  session_id    — Session identifier for conversation continuity (str)
  context       — Additional context passed by the caller (dict)
  classification — Which brain was selected (str)
  messages      — Accumulated conversation messages (list[dict])
  tool_calls    — Tool calls generated by the brain (list[dict])
  tool_results  — Results from executing tool calls (list[dict])
  response      — The final formatted response (str)
  metadata      — Pipeline execution metadata (dict)

Brains:
  market_data   — Live prices, market summaries, trends
  signal_intel  — Signal stats, active signals, performance
  account       — Balance, equity, drawdown, risk state
  strategy      — SMC concepts, gate pipeline, session schedule
  system        — Health checks, provider status, diagnostics
  state         — Compiled market state, regime, conviction, zones
  general       — Lightweight general intelligence fallback
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from marketmate.core.logger import get_logger

log = get_logger("agent.pipeline")

# ─── Optional imports — langgraph / langchain may not be installed ────────────

try:
    from langgraph.graph import StateGraph, END
    _LANGGRAPH_AVAILABLE = True
except ImportError:
    _LANGGRAPH_AVAILABLE = False
    StateGraph = None  # type: ignore[assignment,misc]
    END = None  # type: ignore[assignment]

try:
    from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
    _LANGCHAIN_AVAILABLE = True
except ImportError:
    _LANGCHAIN_AVAILABLE = False
    HumanMessage = None  # type: ignore[assignment,misc]
    AIMessage = None  # type: ignore[assignment,misc]
    SystemMessage = None  # type: ignore[assignment,misc]


# ─── Brain name constants ─────────────────────────────────────────────────────

BRAIN_MARKET_DATA = "market_data"
BRAIN_SIGNAL_INTEL = "signal_intel"
BRAIN_ACCOUNT = "account"
BRAIN_STRATEGY = "strategy"
BRAIN_SYSTEM = "system"
BRAIN_STATE = "state"
BRAIN_GENERAL = "general"

VALID_BRAINS = [
    BRAIN_MARKET_DATA,
    BRAIN_SIGNAL_INTEL,
    BRAIN_ACCOUNT,
    BRAIN_STRATEGY,
    BRAIN_SYSTEM,
    BRAIN_STATE,
    BRAIN_GENERAL,
]


# ─── Routing classification prompt ───────────────────────────────────────────

_CLASSIFICATION_PROMPT = """You are a query router for MATE, a trading intelligence system. Classify the following query into exactly ONE of these categories:

- market_data: Questions about live prices, market summaries, trends, volatility, OHLCV data
- signal_intel: Questions about signals, win rate, performance stats, active trades, PnL
- account: Questions about balance, equity, drawdown, risk state, account info
- strategy: Questions about SMC concepts (BOS, CHoCH, FVG, order blocks), strategy parameters, gates, sessions
- system: Questions about system health, providers, diagnostics, uptime, API status
- state: Questions about market state, bias, conviction, regime, zones, liquidity, state transitions
- general: Everything else — general chat, non-trading questions, greetings, off-topic

Query: "{query}"

Respond with ONLY the category name, nothing else."""


# ═══════════════════════════════════════════════════════════════════════════════
# MateAgentPipeline
# ═══════════════════════════════════════════════════════════════════════════════

class MateAgentPipeline:
    """
    LangGraph-based agent pipeline for the MATE AI system.

    Creates a graph-based workflow that routes queries through
    different brains and tools. When langgraph is not installed,
    falls back to a simple LLM-direct pipeline.

    Usage:
        pipeline = MateAgentPipeline()
        result = await pipeline.run(
            query="What's the price of gold?",
            session_id="user_123",
            context={"chat_id": "456"},
        )
    """

    def __init__(
        self,
        llm_provider: Any = None,
        memory_store: Any = None,
        authority_level: int = 0,
    ) -> None:
        """
        Initialize the agent pipeline.

        Args:
            llm_provider: Optional LLM provider instance. If None, the global
                provider from marketmate.core.llm is used as fallback.
            memory_store: Optional memory store for conversation persistence.
                If None, in-memory dict is used.
            authority_level: Authority level for ops-related tool execution.
                0 = read-only, 1 = safe ops, 2 = destructive.
        """
        self._llm_provider = llm_provider
        self._memory_store = memory_store or {}
        self._authority_level = authority_level
        self._graph = None
        self._compiled_graph = None
        self._query_count: int = 0

        # Build the LangGraph graph if available
        if _LANGGRAPH_AVAILABLE:
            try:
                self._graph = self._build_graph()
                self._compiled_graph = self._graph.compile()
                log.info(
                    "agent_pipeline_initialized",
                    mode="langgraph",
                    authority_level=authority_level,
                )
            except Exception as exc:
                log.warning(
                    "agent_pipeline_graph_build_failed",
                    error=str(exc),
                    fallback="simple",
                )
                self._graph = None
                self._compiled_graph = None
        else:
            log.info(
                "agent_pipeline_initialized",
                mode="simple_fallback",
                reason="langgraph_not_installed",
                authority_level=authority_level,
            )

    # ─── Public API ──────────────────────────────────────────────────────────

    async def run(
        self,
        query: str,
        session_id: str = "",
        context: Optional[dict] = None,
    ) -> dict:
        """
        Run the full agent pipeline on a query.

        If LangGraph is available and the graph was compiled successfully,
        runs through the graph-based pipeline (router → brain → tools →
        formatter). Otherwise falls back to a simple LLM-direct call.

        Args:
            query: The user's query string.
            session_id: Session identifier for conversation continuity.
            context: Additional context dict (chat_id, user info, etc.).

        Returns:
            Dict with keys:
              - response: The formatted response string
              - classification: Which brain was selected
              - tool_calls: List of tool calls made (if any)
              - tool_results: List of tool execution results (if any)
              - metadata: Pipeline execution metadata (latency, mode, etc.)
        """
        self._query_count += 1
        start = time.monotonic()
        context = context or {}

        # Initialise the pipeline state
        state: dict = {
            "query": query,
            "session_id": session_id,
            "context": context,
            "classification": "",
            "messages": [],
            "tool_calls": [],
            "tool_results": [],
            "response": "",
            "metadata": {
                "pipeline_id": f"run_{self._query_count}_{int(start)}",
                "started_at": datetime.now(timezone.utc).isoformat(),
            },
        }

        try:
            if self._compiled_graph is not None:
                # LangGraph pipeline
                result_state = await self._compiled_graph.ainvoke(state)
                response = result_state.get("response", "")
                classification = result_state.get("classification", "")
                tool_calls = result_state.get("tool_calls", [])
                tool_results = result_state.get("tool_results", [])
                mode = "langgraph"
            else:
                # Simple fallback pipeline
                result = await self._run_simple_pipeline(state)
                response = result.get("response", "")
                classification = result.get("classification", BRAIN_GENERAL)
                tool_calls = result.get("tool_calls", [])
                tool_results = result.get("tool_results", [])
                mode = "simple_fallback"

        except Exception as exc:
            log.error(
                "agent_pipeline_run_failed",
                query=query[:80],
                error=str(exc),
                exc_info=True,
            )
            # Last-resort fallback — try a bare LLM call
            response = await self._last_resort_llm_call(query)
            classification = BRAIN_GENERAL
            tool_calls = []
            tool_results = []
            mode = "error_fallback"

        elapsed_ms = round((time.monotonic() - start) * 1000, 1)

        return {
            "response": response,
            "classification": classification,
            "tool_calls": tool_calls,
            "tool_results": tool_results,
            "metadata": {
                **state["metadata"],
                "mode": mode,
                "elapsed_ms": elapsed_ms,
                "completed_at": datetime.now(timezone.utc).isoformat(),
            },
        }

    # ─── Graph Builder ──────────────────────────────────────────────────────

    def _build_graph(self) -> "StateGraph":
        """
        Build the LangGraph state graph.

        Graph structure:
            router → brain → (conditional) → tool_executor → formatter
                             │                                  ▲
                             └──── (skip tools) ────────────────┘

        Returns:
            A compiled StateGraph ready for execution.
        """
        if not _LANGGRAPH_AVAILABLE or StateGraph is None:
            raise RuntimeError("langgraph is not installed")

        graph = StateGraph(dict)

        # Add nodes
        graph.add_node("router", self._route_query)
        graph.add_node("brain", self._execute_brain)
        graph.add_node("tool_executor", self._execute_tools)
        graph.add_node("formatter", self._format_response)

        # Set entry point
        graph.set_entry_point("router")

        # router → brain
        graph.add_edge("router", "brain")

        # brain → tool_executor OR formatter (conditional)
        graph.add_conditional_edges(
            "brain",
            self._should_use_tools,
            {
                True: "tool_executor",
                False: "formatter",
            },
        )

        # tool_executor → formatter
        graph.add_edge("tool_executor", "formatter")

        # formatter → END
        graph.add_edge("formatter", END)

        return graph

    # ─── Node: Router ───────────────────────────────────────────────────────

    async def _route_query(self, state: dict) -> dict:
        """
        Classify the query and route to the appropriate brain.

        Uses the LLM to classify the query into one of the 7 brain
        categories. Falls back to keyword matching if the LLM is
        unavailable.

        Updates state['classification'] with the brain name.
        """
        query = state.get("query", "")
        classification = BRAIN_GENERAL  # default

        # Try LLM-based classification
        try:
            llm = self._get_llm_provider()
            if llm is not None:
                prompt = _CLASSIFICATION_PROMPT.format(query=query)
                result = await llm.chat(
                    system_prompt="You are a precise classifier. Respond with ONLY a single category name.",
                    user_prompt=prompt,
                    max_tokens=20,
                    temperature=0.0,
                )
                raw = result.text.strip().lower()

                # Normalize the classification
                for brain_name in VALID_BRAINS:
                    if brain_name in raw:
                        classification = brain_name
                        break

        except Exception as exc:
            log.warning(
                "agent_router_llm_failed",
                error=str(exc),
                fallback="keyword",
            )
            # Keyword-based fallback
            classification = self._keyword_classify(query)

        log.info(
            "agent_router_classified",
            query=query[:80],
            classification=classification,
        )

        state["classification"] = classification
        return state

    # ─── Node: Brain ────────────────────────────────────────────────────────

    async def _execute_brain(self, state: dict) -> dict:
        """
        Execute the selected brain.

        Dispatches to the appropriate brain module based on
        state['classification']. Each brain returns structured
        data that may include tool calls or direct responses.

        The brain may:
          - Return a direct response (no tools needed)
          - Request tool calls (which will be executed by tool_executor)
          - Return an error (which will be formatted gracefully)
        """
        classification = state.get("classification", BRAIN_GENERAL)
        query = state.get("query", "")
        context = state.get("context", {})

        try:
            if classification == BRAIN_MARKET_DATA:
                result = await self._brain_market_data(query, context)
            elif classification == BRAIN_SIGNAL_INTEL:
                result = await self._brain_signal_intel(query, context)
            elif classification == BRAIN_ACCOUNT:
                result = await self._brain_account(query, context)
            elif classification == BRAIN_STRATEGY:
                result = await self._brain_strategy(query, context)
            elif classification == BRAIN_SYSTEM:
                result = await self._brain_system(query, context)
            elif classification == BRAIN_STATE:
                result = await self._brain_state(query, context)
            else:
                result = await self._brain_general(query, context)

        except Exception as exc:
            log.error(
                "agent_brain_execution_failed",
                classification=classification,
                error=str(exc),
            )
            result = {
                "response": "",
                "tool_calls": [],
                "error": str(exc),
            }

        # Merge brain result into state
        if result.get("response"):
            state["response"] = result["response"]
        if result.get("tool_calls"):
            state["tool_calls"] = result["tool_calls"]
        if result.get("messages"):
            state["messages"].extend(result["messages"])

        return state

    # ─── Conditional Edge: Should use tools? ─────────────────────────────────

    def _should_use_tools(self, state: dict) -> bool:
        """
        Decide if tools are needed based on the brain's output.

        Returns True if the brain generated tool calls that need
        to be executed, False otherwise.
        """
        tool_calls = state.get("tool_calls", [])
        return bool(tool_calls)

    # ─── Node: Tool Executor ────────────────────────────────────────────────

    async def _execute_tools(self, state: dict) -> dict:
        """
        Execute tool calls generated by the brain.

        Iterates through the tool_calls list and executes each one.
        Results are appended to state['tool_results'].

        Supports both MATE tools (market intelligence) and MATE-Ops
        tools (infrastructure monitoring), gated by authority_level.
        """
        tool_calls = state.get("tool_calls", [])
        tool_results: list = state.get("tool_results", [])

        for tc in tool_calls:
            tool_name = tc.get("name", tc.get("function", {}).get("name", ""))
            tool_args = tc.get("args", tc.get("function", {}).get("arguments", {}))

            # Parse args if JSON string
            if isinstance(tool_args, str):
                try:
                    tool_args = json.loads(tool_args)
                except json.JSONDecodeError:
                    tool_args = {}

            log.info("agent_tool_executing", tool=tool_name, args=str(tool_args)[:100])

            try:
                result = await self._dispatch_tool(tool_name, tool_args)
                tool_results.append({
                    "tool": tool_name,
                    "status": "success",
                    "result": result,
                })
            except Exception as exc:
                log.error(
                    "agent_tool_execution_failed",
                    tool=tool_name,
                    error=str(exc),
                )
                tool_results.append({
                    "tool": tool_name,
                    "status": "error",
                    "error": str(exc),
                })

        state["tool_results"] = tool_results
        return state

    # ─── Node: Formatter ────────────────────────────────────────────────────

    async def _format_response(self, state: dict) -> dict:
        """
        Format the final response.

        If the brain already produced a response, uses it directly.
        If tool results are available but no response, synthesizes
        a response from the tool results using the LLM.
        If neither, returns a helpful fallback message.
        """
        existing_response = state.get("response", "")
        tool_results = state.get("tool_results", [])
        query = state.get("query", "")

        if existing_response and not tool_results:
            # Brain already provided a response — use it
            state["response"] = existing_response
            return state

        if tool_results:
            # Synthesize a response from tool results
            try:
                synthesized = await self._synthesize_from_tools(query, tool_results)
                state["response"] = synthesized
            except Exception as exc:
                log.warning(
                    "agent_formatter_synthesis_failed",
                    error=str(exc),
                )
                # Fall back to raw tool results
                state["response"] = self._format_tool_results_raw(tool_results)
            return state

        # No response and no tool results — fallback
        state["response"] = (
            "I wasn't able to process that query. "
            "Could you try rephrasing or ask something else?"
        )
        return state

    # ═════════════════════════════════════════════════════════════════════════
    # Brain Implementations
    # ═════════════════════════════════════════════════════════════════════════

    async def _brain_market_data(self, query: str, context: dict) -> dict:
        """Market Data Brain: prices, summaries, trends."""
        from marketmate.mate.brains.market_data import market_data_brain

        symbol = self._extract_symbol(query, context)
        tool_calls = []

        # Decide which function to call based on query content
        q_lower = query.lower()
        if any(kw in q_lower for kw in ("price", "cost", "how much", "worth", "quote")):
            tool_calls.append({"name": "get_live_price", "args": {"symbol": symbol}})
        if any(kw in q_lower for kw in ("summary", "overview", "trend", "market", "analysis")):
            tool_calls.append({"name": "get_market_summary", "args": {"symbol": symbol}})

        # Default: get both price and summary
        if not tool_calls:
            tool_calls = [
                {"name": "get_live_price", "args": {"symbol": symbol}},
                {"name": "get_market_summary", "args": {"symbol": symbol}},
            ]

        return {"response": "", "tool_calls": tool_calls}

    async def _brain_signal_intel(self, query: str, context: dict) -> dict:
        """Signal Intelligence Brain: stats, active signals, performance."""
        from marketmate.mate.brains.signal_intel import signal_intel_brain

        days = self._extract_days(query, 30)
        tool_calls = []

        q_lower = query.lower()
        if any(kw in q_lower for kw in ("active", "open", "current signal", "running")):
            tool_calls.append({"name": "get_active_signals", "args": {}})
        if any(kw in q_lower for kw in ("stat", "performance", "win rate", "pnl", "track record")):
            tool_calls.append({"name": "get_signal_stats", "args": {"days": days}})

        if not tool_calls:
            tool_calls = [
                {"name": "get_signal_stats", "args": {"days": days}},
                {"name": "get_active_signals", "args": {}},
            ]

        return {"response": "", "tool_calls": tool_calls}

    async def _brain_account(self, query: str, context: dict) -> dict:
        """Account Brain: balance, equity, drawdown, risk."""
        tool_calls = [{"name": "get_account_state", "args": {}}]
        return {"response": "", "tool_calls": tool_calls}

    async def _brain_strategy(self, query: str, context: dict) -> dict:
        """Strategy Brain: SMC concepts, gates, sessions."""
        concept = self._extract_concept(query)
        tool_calls = [{"name": "explain_concept", "args": {"concept": concept}}]
        return {"response": "", "tool_calls": tool_calls}

    async def _brain_system(self, query: str, context: dict) -> dict:
        """System Brain: health, providers, diagnostics."""
        q_lower = query.lower()

        # If this looks like an ops query, include MATE-Ops tools
        if any(kw in q_lower for kw in ("ops", "infrastructure", "monitor", "deploy", "service")):
            from marketmate.mate_ops.tools import MATE_OPS_TOOLS
            # Add ops tools relevant to the query
            tool_calls = [{"name": "get_system_health", "args": {}}]
            # Include level-0 ops tools if authority permits
            if self._authority_level >= 0:
                for ops_tool in MATE_OPS_TOOLS:
                    func = ops_tool.get("function", {})
                    if "check" in func.get("name", ""):
                        tool_calls.append({"name": func["name"], "args": {}})
            return {"response": "", "tool_calls": tool_calls}

        return {"response": "", "tool_calls": [{"name": "get_system_health", "args": {}}]}

    async def _brain_state(self, query: str, context: dict) -> dict:
        """State Intelligence Brain: compiled market state, regime, zones."""
        symbol = self._extract_symbol(query, context)
        tool_calls = []

        q_lower = query.lower()
        if any(kw in q_lower for kw in ("regime", "trending", "ranging")):
            tool_calls.append({"name": "get_market_regime", "args": {}})
        if any(kw in q_lower for kw in ("conviction", "bullish", "bearish", "strength")):
            tool_calls.append({"name": "get_conviction_chart", "args": {}})
        if any(kw in q_lower for kw in ("transition", "change", "flip", "shift")):
            tool_calls.append({"name": "get_state_transitions", "args": {"symbol": symbol}})
        if any(kw in q_lower for kw in ("zone", "order block", "fvg", "fair value")):
            tool_calls.append({"name": "get_zone_state", "args": {"symbol": symbol}})
        if any(kw in q_lower for kw in ("liquidity", "sweep")):
            tool_calls.append({"name": "get_liquidity_state", "args": {"symbol": symbol}})

        # Default: full instrument state
        if not tool_calls:
            tool_calls = [
                {"name": "get_instrument_state", "args": {"symbol": symbol}},
                {"name": "get_market_regime", "args": {}},
            ]

        return {"response": "", "tool_calls": tool_calls}

    async def _brain_general(self, query: str, context: dict) -> dict:
        """General Brain: lightweight general intelligence fallback."""
        try:
            from marketmate.mate.brains.general import general_brain
            result = await general_brain.general_response(query)
            response = result.get("response", "")
            return {"response": response, "tool_calls": []}
        except Exception as exc:
            log.warning("agent_general_brain_failed", error=str(exc))
            # Fall back to direct LLM call
            response = await self._last_resort_llm_call(query)
            return {"response": response, "tool_calls": []}

    # ═════════════════════════════════════════════════════════════════════════
    # Tool Dispatch
    # ═════════════════════════════════════════════════════════════════════════

    async def _dispatch_tool(self, tool_name: str, args: dict) -> dict:
        """
        Dispatch a tool call to the appropriate executor.

        Supports both MATE intelligence tools and MATE-Ops tools.
        Ops tools are gated by the pipeline's authority_level.
        """
        # ── MATE Intelligence Tools ──────────────────────────────────────
        if tool_name == "get_live_price":
            from marketmate.mate.brains.market_data import market_data_brain
            symbol = self._resolve_symbol(args.get("symbol", "XAUUSD"))
            return await market_data_brain.get_live_price(symbol)

        elif tool_name == "get_market_summary":
            from marketmate.mate.brains.market_data import market_data_brain
            symbol = self._resolve_symbol(args.get("symbol", "XAUUSD"))
            return await market_data_brain.get_market_summary(symbol)

        elif tool_name == "get_signal_stats":
            from marketmate.mate.brains.signal_intel import signal_intel_brain
            return await signal_intel_brain.get_signal_stats(days=args.get("days", 30))

        elif tool_name == "get_active_signals":
            from marketmate.mate.brains.signal_intel import signal_intel_brain
            return await signal_intel_brain.get_active_signals()

        elif tool_name == "get_account_state":
            from marketmate.mate.brains.account import account_brain
            return await account_brain.get_state()

        elif tool_name == "explain_concept":
            from marketmate.mate.brains.strategy import strategy_brain
            return await strategy_brain.explain_concept(concept=args.get("concept", ""))

        elif tool_name == "get_system_health":
            from marketmate.mate.brains.system import system_brain
            return await system_brain.get_system_health()

        elif tool_name == "get_instrument_state":
            from marketmate.mate.brains.state_intel import state_intel_brain
            symbol = self._resolve_symbol(args.get("symbol", "XAUUSD"))
            return await state_intel_brain.get_instrument_state(symbol=symbol)

        elif tool_name == "get_market_regime":
            from marketmate.mate.brains.state_intel import state_intel_brain
            return await state_intel_brain.get_market_regime()

        elif tool_name == "get_conviction_chart":
            from marketmate.mate.brains.state_intel import state_intel_brain
            return await state_intel_brain.get_conviction_chart()

        elif tool_name == "get_state_transitions":
            from marketmate.mate.brains.state_intel import state_intel_brain
            return await state_intel_brain.get_state_transitions(
                symbol=args.get("symbol", "")
            )

        elif tool_name == "get_zone_state":
            from marketmate.mate.brains.state_intel import state_intel_brain
            symbol = self._resolve_symbol(args.get("symbol", "XAUUSD"))
            return await state_intel_brain.get_zone_state(symbol=symbol)

        elif tool_name == "get_liquidity_state":
            from marketmate.mate.brains.state_intel import state_intel_brain
            symbol = self._resolve_symbol(args.get("symbol", "XAUUSD"))
            return await state_intel_brain.get_liquidity_state(symbol=symbol)

        # ── MATE-Ops Tools (gated by authority_level) ────────────────────
        elif tool_name == "check_health":
            self._require_authority(0)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.check_health()

        elif tool_name == "check_ollama_status":
            self._require_authority(0)
            from marketmate.mate_ops.observer import telemetry_collector
            obs = await telemetry_collector.check_ollama_health()
            return {"status": obs.status, "message": obs.message, "details": obs.details}

        elif tool_name == "read_logs":
            self._require_authority(0)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.read_logs(**args)

        elif tool_name == "check_metrics":
            self._require_authority(0)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.check_metrics(**args)

        elif tool_name == "check_website":
            self._require_authority(0)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.check_website(**args)

        elif tool_name == "restart_service":
            self._require_authority(1)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.restart_service(**args)

        elif tool_name == "clear_cache":
            self._require_authority(1)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.clear_cache(**args)

        elif tool_name == "notify_team":
            self._require_authority(1)
            from marketmate.mate_ops.agent import MATEOpsAgent
            ops = MATEOpsAgent(authority_level=self._authority_level)
            return await ops.notify_team(**args)

        else:
            return {"error": f"Unknown tool: {tool_name}"}

    # ═════════════════════════════════════════════════════════════════════════
    # Simple Fallback Pipeline (when langgraph is not installed)
    # ═════════════════════════════════════════════════════════════════════════

    async def _run_simple_pipeline(self, state: dict) -> dict:
        """
        Simple pipeline without LangGraph — runs the same logical steps
        sequentially: classify → brain → tools → format.
        """
        # Step 1: Route
        state = await self._route_query(state)

        # Step 2: Execute brain
        state = await self._execute_brain(state)

        # Step 3: Execute tools if needed
        if self._should_use_tools(state):
            state = await self._execute_tools(state)

        # Step 4: Format response
        state = await self._format_response(state)

        return state

    # ═════════════════════════════════════════════════════════════════════════
    # LLM Helpers
    # ═════════════════════════════════════════════════════════════════════════

    def _get_llm_provider(self) -> Any:
        """Get the LLM provider — injected or global fallback."""
        if self._llm_provider is not None:
            return self._llm_provider

        try:
            from marketmate.core.llm import llm_provider
            return llm_provider
        except ImportError:
            return None

    async def _last_resort_llm_call(self, query: str) -> str:
        """
        Last-resort fallback: call the LLM directly with no tools.
        """
        try:
            llm = self._get_llm_provider()
            if llm is not None:
                result = await llm.chat(
                    system_prompt=(
                        "You are MATE, a helpful AI assistant for the "
                        "MarketMate trading platform. Be concise and helpful."
                    ),
                    user_prompt=query,
                    max_tokens=800,
                    temperature=0.5,
                )
                return result.text
        except Exception as exc:
            log.error("agent_last_resort_llm_failed", error=str(exc))

        return (
            "I'm having trouble processing your request right now. "
            "Please try again in a moment."
        )

    async def _synthesize_from_tools(
        self, query: str, tool_results: list
    ) -> str:
        """
        Synthesize a human-readable response from tool results using the LLM.
        """
        results_text = json.dumps(tool_results, default=str, indent=2)

        # Truncate if very large
        if len(results_text) > 8000:
            results_text = results_text[:8000] + "\n... (truncated)"

        prompt = (
            f"Based on the following tool results, provide a concise, "
            f"conversational answer to the user's question.\n\n"
            f"Question: {query}\n\n"
            f"Tool Results:\n{results_text}\n\n"
            f"Provide a clear, helpful response. Do not mention tools "
            f"or internal processes."
        )

        try:
            llm = self._get_llm_provider()
            if llm is not None:
                result = await llm.chat(
                    system_prompt="You are MATE, a trading AI assistant. Be concise and accurate.",
                    user_prompt=prompt,
                    max_tokens=1200,
                    temperature=0.4,
                )
                return result.text
        except Exception as exc:
            log.warning("agent_synthesis_failed", error=str(exc))

        # Fallback: format raw results
        return self._format_tool_results_raw(tool_results)

    # ═════════════════════════════════════════════════════════════════════════
    # Utility Methods
    # ═════════════════════════════════════════════════════════════════════════

    @staticmethod
    def _keyword_classify(query: str) -> str:
        """
        Keyword-based classification fallback when LLM is unavailable.

        Uses simple pattern matching to assign a brain category.
        """
        q = query.lower()

        market_data_kw = (
            "price", "cost", "how much", "worth", "quote", "candle",
            "ohlc", "volatility", "trend", "market", "live", "chart",
        )
        signal_kw = (
            "signal", "win rate", "performance", "pnl", "profit",
            "active", "open trade", "stats", "track record",
        )
        account_kw = (
            "balance", "equity", "drawdown", "account", "deposit",
            "margin", "risk state",
        )
        strategy_kw = (
            "bos", "choch", "fvg", "order block", "sweep", "liquidity",
            "smart money", "smc", "gate", "session", "strategy",
            "concept", "explain",
        )
        system_kw = (
            "health", "system", "api", "uptime", "provider", "status",
            "diagnostic", "ops", "monitor", "service",
        )
        state_kw = (
            "state", "bias", "conviction", "regime", "zone", "instrument",
            "transitions", "market state",
        )

        if any(kw in q for kw in market_data_kw):
            return BRAIN_MARKET_DATA
        if any(kw in q for kw in signal_kw):
            return BRAIN_SIGNAL_INTEL
        if any(kw in q for kw in account_kw):
            return BRAIN_ACCOUNT
        if any(kw in q for kw in strategy_kw):
            return BRAIN_STRATEGY
        if any(kw in q for kw in system_kw):
            return BRAIN_SYSTEM
        if any(kw in q for kw in state_kw):
            return BRAIN_STATE

        return BRAIN_GENERAL

    @staticmethod
    def _extract_symbol(query: str, context: dict) -> str:
        """Extract a trading symbol from the query or context."""
        from marketmate.mate.agent import SYMBOL_ALIASES

        # Check context first
        symbol = context.get("symbol", "")
        if symbol:
            return MateAgentPipeline._resolve_symbol(symbol)

        # Search in query
        q_lower = query.lower()
        for alias, canonical in SYMBOL_ALIASES.items():
            if alias in q_lower:
                return canonical

        # Check for direct symbol mentions
        known_symbols = [
            "XAUUSD", "XAGUSD", "EURUSD", "GBPUSD", "USDJPY",
            "BTCUSD", "ETHUSD",
        ]
        for sym in known_symbols:
            if sym.lower() in q_lower:
                return sym

        return "XAUUSD"  # default

    @staticmethod
    def _resolve_symbol(raw: str) -> str:
        """Resolve a symbol name or alias to its canonical form."""
        from marketmate.mate.agent import SYMBOL_ALIASES

        raw_upper = raw.upper().strip()
        # Direct match first
        known = [
            "XAUUSD", "XAGUSD", "EURUSD", "GBPUSD", "USDJPY",
            "BTCUSD", "ETHUSD",
        ]
        for sym in known:
            if raw_upper == sym:
                return sym

        return SYMBOL_ALIASES.get(raw.lower().strip(), raw_upper)

    @staticmethod
    def _extract_days(query: str, default: int = 30) -> int:
        """Extract a lookback period in days from the query."""
        q_lower = query.lower()

        day_map = {
            "today": 1, "1 day": 1, "one day": 1,
            "week": 7, "7 days": 7, "this week": 7,
            "two weeks": 14, "14 days": 14,
            "month": 30, "30 days": 30, "this month": 30,
            "quarter": 90, "90 days": 90,
            "year": 365, "365 days": 365, "this year": 365,
        }

        for phrase, days in day_map.items():
            if phrase in q_lower:
                return days

        return default

    @staticmethod
    def _extract_concept(query: str) -> str:
        """Extract a trading concept from the query."""
        q_lower = query.lower()

        concept_map = {
            "bos": "bos",
            "break of structure": "bos",
            "choch": "choch",
            "change of character": "choch",
            "fvg": "fvg",
            "fair value gap": "fvg",
            "order block": "order_block",
            "ob": "order_block",
            "sweep": "sweep",
            "liquidity": "liquidity",
            "mitigation": "mitigation",
            "displacement": "displacement",
            "inducement": "inducement",
            "smc": "smc",
            "smart money concepts": "smc",
        }

        for phrase, concept in concept_map.items():
            if phrase in q_lower:
                return concept

        # Return the query itself as the concept for the strategy brain to handle
        return query

    def _require_authority(self, required_level: int) -> None:
        """Raise PermissionError if current authority is insufficient."""
        if self._authority_level < required_level:
            raise PermissionError(
                f"Authority level {self._authority_level} insufficient "
                f"(requires {required_level})"
            )

    @staticmethod
    def _format_tool_results_raw(tool_results: list) -> str:
        """Format tool results as a readable text when LLM synthesis fails."""
        lines = []
        for tr in tool_results:
            tool_name = tr.get("tool", "unknown")
            status = tr.get("status", "unknown")

            if status == "success":
                result = tr.get("result", {})
                if isinstance(result, dict):
                    formatted = json.dumps(result, default=str, indent=2)
                else:
                    formatted = str(result)
                lines.append(f"**{tool_name}**:\n{formatted}")
            else:
                error = tr.get("error", "Unknown error")
                lines.append(f"**{tool_name}**: Error — {error}")

        return "\n\n".join(lines) if lines else "No results available."

    # ─── Introspection ─────────────────────────────────────────────────────

    @property
    def status(self) -> dict:
        """Return pipeline status summary."""
        return {
            "module": "agent.pipeline",
            "architecture": "langgraph" if self._compiled_graph else "simple_fallback",
            "langgraph_available": _LANGGRAPH_AVAILABLE,
            "langchain_available": _LANGCHAIN_AVAILABLE,
            "authority_level": self._authority_level,
            "total_queries": self._query_count,
            "valid_brains": VALID_BRAINS,
        }
