"""
marketmate/execution/executor.py
─────────────────────────────────
Simulated Trade Execution Engine

Migrated from execution/sim_executor.py. Key changes:
  - All imports use marketmate. prefix
  - Uses SignalRepository from marketmate.db.repositories.signals
    instead of the direct db.database module
  - Uses EventBus for trade_opened events

Replaces MetaTrader 5 entirely. No broker connections, no terminal,
no external APIs. Runs safely on any free-tier web service.

HOW IT WORKS
────────────
When a signal passes all 8 gates:

  1. SimExecutor.execute() is called with the Signal object.
  2. A virtual trade record is written to MongoDB immediately.
     Status = OPEN.  Entry = signal.entry_mid (zone midpoint).
  3. SimExecutor returns a SimExecutionResult confirming the fill.
  4. The trade evaluation loop (Scheduler, every 10 min) then monitors
     the virtual trade using real market prices until SL or TP is hit.

ENTRY PRICE
───────────
Entry is set to signal.entry_mid (the midpoint of the entry zone).
This is conservative — it assumes a fill at the centre of the zone
rather than the optimal edge. This gives slightly pessimistic P&L
estimates, which is preferred for training data quality.

NO LOOK-AHEAD
─────────────
The sim executor only reads prices that are already in the Signal
object (derived from historical candles). It does NOT fetch any
forward prices at execution time.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from marketmate.core.config import cfg
from marketmate.core.logger import get_logger
from marketmate.core.events import EventBus, event_bus as _default_bus, EventType
from marketmate.db.repositories.signals import SignalRepository
from marketmate.strategy.models import Signal

log = get_logger("sim_executor")


# ─── Result type ─────────────────────────────────────────────────────────────

@dataclass
class SimExecutionResult:
    """
    Returned by SimExecutor.execute().
    Mirrors the fields used by downstream components (training_logger, main.py)
    so swapping in a real executor later requires no interface changes.
    """
    success:      bool
    signal_id:    str
    pair:         str                  # from signal (config-driven, never hardcoded)
    direction:    str                  # "BUY" | "SELL"
    lot_size:     float                # from cfg.sim.lot_size (informational)
    entry_price:  float                # zone midpoint
    stop_loss:    float
    take_profits: list[float]          # [tp1, tp2] or [tp1, tp2, tp3]
    error_msg:    str
    executed_at:  str                  # ISO 8601 UTC


# ─── Executor ────────────────────────────────────────────────────────────────

class SimExecutor:
    """
    Lightweight virtual trade recorder.

    The class has no connection state — every execute() call is independent.
    There is no concept of "enabled/disabled"; if the class is instantiated,
    it is always active. Use cfg.app settings to gate when signals fire.
    """

    def __init__(
        self,
        signal_repo: Optional[SignalRepository] = None,
        event_bus: Optional[EventBus] = None,
    ) -> None:
        self.signal_repo = signal_repo or SignalRepository()
        self.event_bus   = event_bus or _default_bus

    async def execute(
        self,
        signal: Signal,
    ) -> SimExecutionResult:
        """
        Record a virtual trade and return immediately.

        Parameters
        ----------
        signal : Signal object generated by the gate engine.

        Returns
        -------
        SimExecutionResult — always success=True unless a DB write fails.
        """
        entry_price  = signal.entry_mid
        take_profits = [tp for tp in [signal.tp1, signal.tp2, signal.tp3] if tp]
        executed_at  = datetime.now(timezone.utc).isoformat()

        try:
            # Activate the signal record immediately (PENDING → OPEN).
            # This simulates an instant limit-order fill at entry_mid.
            await self.signal_repo.activate_virtual_trade(
                signal_id=signal.id,
                entry_price=entry_price,
            )

            log.info(
                "sim_trade_opened",
                signal_id=signal.id,
                pair=signal.symbol,
                direction=signal.direction,
                entry=round(entry_price, 4),
                sl=round(signal.stop_loss, 4),
                tp1=round(signal.tp1, 4),
                lot=cfg.sim.lot_size,
            )

            # Emit TRADE_OPENED event via EventBus
            await self.event_bus.emit(
                EventType.TRADE_OPENED,
                {
                    "signal_id":    signal.id,
                    "symbol":       signal.symbol,
                    "direction":    signal.direction,
                    "entry_price":  entry_price,
                    "stop_loss":    signal.stop_loss,
                    "tp1":          signal.tp1,
                    "tp2":          signal.tp2,
                    "tp3":          getattr(signal, "tp3", None),
                    "lot_size":     cfg.sim.lot_size,
                    "executed_at":  executed_at,
                },
            )

            return SimExecutionResult(
                success=True,
                signal_id=signal.id,
                pair=signal.symbol,
                direction=signal.direction,
                lot_size=cfg.sim.lot_size,
                entry_price=entry_price,
                stop_loss=signal.stop_loss,
                take_profits=take_profits,
                error_msg="",
                executed_at=executed_at,
            )

        except Exception as exc:
            log.error("sim_execute_failed", signal_id=signal.id, error=str(exc))
            return SimExecutionResult(
                success=False,
                signal_id=signal.id,
                pair=signal.symbol,
                direction=signal.direction,
                lot_size=cfg.sim.lot_size,
                entry_price=0.0,
                stop_loss=0.0,
                take_profits=[],
                error_msg=str(exc),
                executed_at=executed_at,
            )


# ─── Singleton ────────────────────────────────────────────────────────────────

sim_executor = SimExecutor()
