'use client'

import { motion } from 'framer-motion'
import { AlertTriangle } from 'lucide-react'

const fadeInUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' as const } },
}

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.08 } },
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: [
      {
        text: 'By accessing or using MarketMate\'s services, including our website, API, documentation, and related products (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Services.',
      },
      {
        text: 'These Terms constitute a legally binding agreement between you ("User," "you," or "your") and MarketMate ("we," "our," or "us"). We reserve the right to update these Terms at any time as described in Section 9.',
      },
    ],
  },
  {
    title: '2. Service Description',
    content: [
      {
        text: 'MarketMate provides a market intelligence platform that delivers structured, scored, and interpretable market signals through a real-time API. Our services include:',
      },
      {
        subtitle: 'Market Intelligence API',
        text: 'Real-time and on-demand access to market signals, conviction scores, and analytical outputs generated by our 5-brain architecture and 8-gate validation pipeline.',
      },
      {
        subtitle: 'MATE AI Interpreter',
        text: 'An AI-powered market interpretation engine that synthesizes validated pipeline outputs into human-readable narratives, contextual analysis, and actionable intelligence.',
      },
      {
        subtitle: 'WebSocket Streams',
        text: 'Real-time streaming connections for live signal delivery, market state updates, and event-driven notifications.',
      },
      {
        subtitle: 'Dashboard & Developer Tools',
        text: 'Web-based interfaces for account management, API key administration, usage monitoring, and signal visualization.',
      },
      {
        text: 'MarketMate reserves the right to modify, suspend, or discontinue any aspect of the Services at any time, with reasonable notice where practicable.',
      },
    ],
  },
  {
    title: '3. API Usage & Rate Limits',
    content: [
      {
        subtitle: 'Rate Limits',
        text: 'API access is subject to rate limits that vary by subscription plan. Rate limits are enforced per API key and are measured in requests per minute and requests per day. Exceeding rate limits will result in HTTP 429 responses. Current rate limits are documented in our API documentation and may be adjusted with 30 days\' notice.',
      },
      {
        subtitle: 'Fair Use',
        text: 'You agree to use the API in a manner consistent with normal, reasonable usage patterns. This includes, but is not limited to: not making excessive or redundant requests, not implementing retry logic without exponential backoff, not using multiple API keys to circumvent rate limits, and not attempting to scrape or bulk-download historical data beyond the limits specified in your plan.',
      },
      {
        subtitle: 'Prohibited Uses',
        text: 'You may not: (a) resell, sublicense, or redistribute MarketMate data or signals without explicit written authorization; (b) use the Services to build competing intelligence products; (c) attempt to reverse-engineer, decompile, or extract the algorithms, models, or methodologies underlying our signal generation pipeline; (d) use the Services for any illegal purpose or in violation of any applicable financial regulations.',
      },
      {
        subtitle: 'Data Attribution',
        text: 'If you display or redistribute MarketMate signals or derived insights in any public-facing product, you must provide appropriate attribution as specified in our branding guidelines. Enterprise customers may negotiate custom attribution terms.',
      },
    ],
  },
  {
    title: '4. Intellectual Property',
    content: [
      {
        text: 'MarketMate and its licensors retain all right, title, and interest in and to the Services, including all intellectual property rights therein. This includes, without limitation: our 5-brain architecture, 8-gate pipeline logic, MATE AI interpreter models, signal generation algorithms, user interface designs, documentation, and the MarketMate brand and trademarks.',
      },
      {
        text: 'Your use of the Services does not grant you any ownership rights to MarketMate\'s intellectual property. API responses, market signals, and analytical outputs are licensed to you for the duration of your subscription and may be used solely within the scope of the permitted uses described in these Terms.',
      },
      {
        text: 'You retain all intellectual property rights in any applications, tools, or products you build using MarketMate data, subject to the licensing and attribution requirements described in Section 3.',
      },
    ],
  },
  {
    title: '5. Disclaimer — Not Financial Advice',
    content: [
      {
        text: 'IMPORTANT: MarketMate provides market intelligence and analytical tools. We do NOT provide financial advice, investment recommendations, or trading signals in the regulatory sense.',
      },
      {
        text: 'Our conviction scores, market interpretations, and analytical outputs are informational products generated by automated systems. They reflect the output of our signal processing pipeline based on available market data and algorithmic models. They do not constitute offers, solicitations, or recommendations to buy, sell, or hold any financial instrument.',
      },
      {
        text: 'Past performance and historical signal accuracy do not guarantee future results. Market conditions can change rapidly, and our signals may not reflect the most current market state at the exact moment you receive them due to processing latency, data feed delays, or system maintenance.',
      },
      {
        text: 'You are solely responsible for your trading and investment decisions. You should not rely solely on MarketMate outputs when making financial decisions. Always conduct your own due diligence and consult with qualified financial advisors before making investment decisions.',
      },
      {
        text: 'MarketMate is not a registered investment advisor, broker-dealer, or financial planner under the laws of any jurisdiction. Our Services are not intended to be used as the sole basis for any financial decision.',
      },
    ],
  },
  {
    title: '6. Limitation of Liability',
    content: [
      {
        text: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MARKETMATE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES, INCLUDING BUT NOT LIMITED TO: TRADING LOSSES, MISSED OPPORTUNITIES, DATA INACCURACIES, SERVICE INTERRUPTIONS, OR UNAUTHORIZED ACCESS TO YOUR ACCOUNT.',
      },
      {
        text: 'Our total cumulative liability to you for all claims arising out of or related to the Services shall not exceed the total fees you paid to MarketMate during the twelve (12) months preceding the event giving rise to the claim.',
      },
      {
        text: 'This limitation of liability applies regardless of the legal theory under which the claim is asserted, whether in contract, tort, strict liability, or otherwise, and even if MarketMate has been advised of the possibility of such damages.',
      },
    ],
  },
  {
    title: '7. Account Termination',
    content: [
      {
        text: 'You may terminate your account at any time through the dashboard or by contacting support. Upon termination, your API keys will be immediately revoked, and you will lose access to the Services. We will retain your data for 30 days following termination to allow for potential reactivation, after which it will be permanently deleted.',
      },
      {
        text: 'MarketMate reserves the right to suspend or terminate accounts that violate these Terms, exhibit suspicious or abusive usage patterns, or pose a security risk. We will make reasonable efforts to provide notice before termination, except in cases involving security threats or illegal activity.',
      },
      {
        text: 'Termination does not relieve you of obligations accrued prior to termination, including payment obligations and confidentiality requirements.',
      },
    ],
  },
  {
    title: '8. Modifications to Terms',
    content: [
      {
        text: 'We may modify these Terms from time to time. When we make material changes, we will notify you via email or through a prominent notice on our website at least 30 days before the changes take effect. Your continued use of the Services after the effective date constitutes acceptance of the modified Terms.',
      },
      {
        text: 'For changes that are purely beneficial or clarifying in nature (such as adding new features or correcting typographical errors), we may implement them without advance notice.',
      },
    ],
  },
  {
    title: '9. Governing Law',
    content: [
      {
        text: 'These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved first through good-faith negotiation, and if negotiation fails, through binding arbitration in accordance with the rules of the applicable arbitration body.',
      },
      {
        text: 'You agree to waive any right to a jury trial and to participate in class action lawsuits related to the Services.',
      },
    ],
  },
  {
    title: '10. Contact',
    content: [
      {
        text: 'If you have questions about these Terms of Service, please contact us at:',
      },
      {
        text: 'Email: legal@marketmate.io',
      },
      {
        text: 'For API-specific inquiries: api-support@marketmate.io',
      },
      {
        text: 'For security concerns: security@marketmate.io',
      },
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-white">
      {/* Nav */}
      <nav className="border-b border-white/[0.06] bg-zinc-950/80 backdrop-blur-md">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex h-16 items-center justify-between">
          <a href="/" className="flex items-center gap-2.5">
            <img src="/logo.png" alt="MarketMate" width={28} height={28} className="rounded-md" />
            <span className="text-lg font-bold text-white">
              Market<span className="text-emerald-400">Mate</span>
            </span>
          </a>
          <a href="/" className="text-sm text-zinc-400 hover:text-emerald-400 transition-colors">
            &larr; Back to Home
          </a>
        </div>
      </nav>

      {/* Content */}
      <main className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-16">
        {/* Header */}
        <motion.div
          initial="hidden"
          animate="visible"
          variants={staggerContainer}
          className="mb-12"
        >
          <motion.p variants={fadeInUp} className="text-emerald-400 text-sm font-semibold tracking-wider uppercase mb-4">
            Legal
          </motion.p>
          <motion.h1 variants={fadeInUp} className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            Terms of Service
          </motion.h1>
          <motion.p variants={fadeInUp} className="text-zinc-500 text-sm">
            Last updated: March 1, 2026
          </motion.p>
        </motion.div>

        {/* Important disclaimer callout */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={fadeInUp}
          className="mb-12 rounded-xl border border-amber-400/20 bg-amber-400/[0.04] p-6 flex gap-4"
        >
          <AlertTriangle className="w-6 h-6 text-amber-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-amber-400 mb-1">Important Disclaimer</p>
            <p className="text-zinc-400 text-sm leading-relaxed">
              MarketMate provides market intelligence and analytical tools — NOT financial advice.
              Our signals, conviction scores, and MATE AI outputs are informational products
              generated by automated systems. They do not constitute investment recommendations or
              trading advice. You are solely responsible for your financial decisions.
            </p>
          </div>
        </motion.div>

        {/* Sections */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-50px' }}
          variants={staggerContainer}
          className="space-y-10"
        >
          {sections.map((section) => (
            <motion.section key={section.title} variants={fadeInUp}>
              <h2 className="text-xl font-bold mb-4 text-white">{section.title}</h2>
              <div className="space-y-4">
                {section.content.map((item, i) => (
                  <div key={i}>
                    {item.subtitle && (
                      <h3 className="text-sm font-semibold text-emerald-400 mb-1.5">
                        {item.subtitle}
                      </h3>
                    )}
                    <p className="text-zinc-400 text-sm leading-relaxed">{item.text}</p>
                  </div>
                ))}
              </div>
            </motion.section>
          ))}
        </motion.div>

        {/* Bottom callout */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={fadeInUp}
          className="mt-12 rounded-xl border border-white/[0.06] bg-white/[0.02] p-6"
        >
          <p className="text-zinc-400 text-sm leading-relaxed">
            By using MarketMate&apos;s services, you acknowledge that you have read, understood, and
            agree to be bound by these Terms of Service. If you have any questions, please contact
            us at{' '}
            <a
              href="mailto:legal@marketmate.io"
              className="text-emerald-400 hover:text-emerald-300 transition-colors"
            >
              legal@marketmate.io
            </a>
            .
          </p>
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/[0.06] py-8 text-center">
        <a href="/" className="text-sm text-zinc-400 hover:text-emerald-400 transition-colors">
          &larr; Back to MarketMate
        </a>
        <p className="text-xs text-zinc-600 mt-2">&copy; 2026 MarketMate. All rights reserved.</p>
      </footer>
    </div>
  )
}
